linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - goconst
    - goimports
    - gosec
    - ifshort
    - revive