basePath: /api
definitions:
  api.ReturnedData:
    properties:
      data:
        description: |-
          Anything you want to pass to the frontend, but make it simple and necessary
          If there's nothing to return, this field will be omitted
        type: object
      status:
        description: |-
          A simple string indicating the status.
          Is it ok, or some error occurs? If so, what is the error?
          It should be "ok" is everything goes fine
        type: string
    type: object
  github.com_AsterNighT_software-engineering-backend_pkg_cases.Case:
    properties:
      complaint:
        type: string
      diagnosis:
        type: string
      id:
        description: Every object should have ID
        type: integer
      patientID:
        description: A has many relationship should be on this
        type: integer
      prescriptions:
        items:
          $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Prescription'
        type: array
    type: object
  github.com_AsterNighT_software-engineering-backend_pkg_cases.Prescription:
    properties:
      caseID:
        type: integer
      details:
        type: string
      id:
        type: integer
    type: object
  pkg_cases.Case:
    properties:
      complaint:
        type: string
      diagnosis:
        type: string
      id:
        description: Every object should have ID
        type: integer
      patientID:
        description: A has many relationship should be on this
        type: integer
      prescriptions:
        items:
          $ref: '#/definitions/pkg_cases.Prescription'
        type: array
    type: object
  pkg_cases.Prescription:
    properties:
      caseID:
        type: integer
      details:
        type: string
      id:
        type: integer
    type: object
host: localhost:12448
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /account:
    post:
      parameters:
      - description: user e-mail
        in: path
        name: Email
        required: true
        type: string
      - description: user password
        in: path
        name: Passwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: login using email and passwd
      tags:
      - Account
  /account/{id}:
    post:
      description: can only be called during logged-in status since there is no password
        check
      parameters:
      - description: user e-mail
        in: path
        name: Email
        required: true
        type: string
      - description: user password (the new one)
        in: path
        name: Passwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: the interface of modifying password
      tags:
      - Account
  /account/account_table:
    post:
      description: will check primarykey other, then add to account_list if possible
      parameters:
      - description: user e-mail
        in: path
        name: Email
        required: true
        type: string
      - description: user type
        in: path
        name: Type
        required: true
        type: string
      - description: user name
        in: path
        name: Name
        required: true
        type: string
      - description: user password
        in: path
        name: Passwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: create and account based on email(as id), type, name and password
      tags:
      - Account
  /case/{id}:
    get:
      parameters:
      - description: case ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  $ref: '#/definitions/pkg_cases.Case'
              type: object
      summary: Get case by case id
  /ping:
    get:
      description: respond to a ping request from client
      produces:
      - application/json
      responses:
        "200":
          description: Good, server is up
          schema:
            $ref: '#/definitions/api.ReturnedData'
      summary: Test server up statue
swagger: "2.0"
