basePath: /api
definitions:
  api.ReturnedData:
    properties:
      data:
        description: |-
          Anything you want to pass to the frontend, but make it simple and necessary
          If there's nothing to return, this field will be omitted
        type: object
      status:
        description: |-
          A simple string indicating the status.
          Is it ok, or some error occurs? If so, what is the error?
          It should be "ok" is everything goes fine
        type: string
    type: object
  github.com_AsterNighT_software-engineering-backend_pkg_cases.Case:
    properties:
      complaint:
        description: Use urls to locate pictures
        type: string
      department:
        type: string
      diagnosis:
        type: string
      doctorID:
        type: integer
      id:
        description: Every object should have ID
        type: integer
      pastHistory:
        type: string
      patientID:
        description: A has many relationship should be on this
        type: integer
      prescriptions:
        items:
          $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Prescription'
        type: array
      previousCase:
        $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
        description: Previous case (the lastest one). If there is none prevous case,
          set nil
      previousCaseID:
        type: integer
    type: object
  github.com_AsterNighT_software-engineering-backend_pkg_cases.Prescription:
    properties:
      caseID:
        type: integer
      details:
        type: string
      id:
        type: integer
    type: object
  pkg_cases.Case:
    properties:
      complaint:
        description: Use urls to locate pictures
        type: string
      department:
        type: string
      diagnosis:
        type: string
      doctorID:
        type: integer
      id:
        description: Every object should have ID
        type: integer
      pastHistory:
        type: string
      patientID:
        description: A has many relationship should be on this
        type: integer
      prescriptions:
        items:
          $ref: '#/definitions/pkg_cases.Prescription'
        type: array
      previousCase:
        $ref: '#/definitions/pkg_cases.Case'
        description: Previous case (the lastest one). If there is none prevous case,
          set nil
      previousCaseID:
        type: integer
    type: object
  pkg_cases.Prescription:
    properties:
      caseID:
        type: integer
      details:
        type: string
      id:
        type: integer
    type: object
host: localhost:12448
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /{patientid}/case:
    get:
      parameters:
      - description: patient ID
        in: path
        name: patientID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get the lastest case ID
      tags:
      - Case
  /{patientid}/case/department:
    get:
      parameters:
      - description: patient ID
        in: path
        name: patientID
        required: true
        type: integer
      - description: department name
        in: path
        name: department
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/api.ReturnedData'
              - properties:
                  data:
                    items:
                      type: integer
                    type: array
                type: object
            type: array
      summary: Get a case ID list
      tags:
      - Case
  /case:
    post:
      parameters:
      - description: patient ID, doctor ID, department name and other case details
        in: body
        name: caseDetail
        required: true
        schema:
          $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReturnedData'
      summary: New a case
      tags:
      - Case
  /case/{caseid}:
    get:
      parameters:
      - description: case IDs
        in: query
        items:
          type: integer
        name: caseIDList
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
                  type: array
              type: object
      summary: Get case by a case-id list
      tags:
      - Case
    put:
      parameters:
      - description: case ID and updated details
        in: body
        name: caseDetail
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
              type: object
      summary: Update case
      tags:
      - Case
  /case/{caseid}/prescription:
    get:
      parameters:
      - description: case ID
        in: path
        name: caseID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/pkg_cases.Prescription'
                  type: array
              type: object
      summary: Get prescriptions by case id
      tags:
      - Case
    post:
      parameters:
      - description: case ID and prescription details
        in: body
        name: prescriptionDetail
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  $ref: '#/definitions/pkg_cases.Prescription'
              type: object
      summary: New a prescrition
      tags:
      - Case
  /case/{caseid}/prescription/{prescriptionid}:
    get:
      parameters:
      - description: prescription ID
        in: path
        name: prescriptionID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  $ref: '#/definitions/pkg_cases.Prescription'
              type: object
      summary: Get prescription by prescription id
      tags:
      - Case
  /case/{currentcaseid}:
    get:
      parameters:
      - description: current case ID
        in: path
        name: caseID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
                  type: array
              type: object
      summary: Get prevoius cases by current case ID
      tags:
      - Case
  /case/department:
    get:
      parameters:
      - description: patient ID
        in: path
        name: patientID
        required: true
        type: integer
      - description: department name
        in: path
        name: department
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.ReturnedData'
            - properties:
                data:
                  $ref: '#/definitions/github.com_AsterNighT_software-engineering-backend_pkg_cases.Case'
              type: object
      summary: Get lastest case by department name
      tags:
      - Case
  /ping:
    get:
      description: respond to a ping request from client
      produces:
      - application/json
      responses:
        "200":
          description: Good, server is up
          schema:
            $ref: '#/definitions/api.ReturnedData'
      summary: Test server up statue
swagger: "2.0"
