# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: v1.38
          skip-go-installation: true
          args: --out-format github-actions 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test ./...
  update-coverage: 
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: b619116e-c655-4475-bb4a-147415258236
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: | 
          go test -race -coverprofile=coverage.txt -covermode=atomic ./... 
          bash <(curl -s https://codecov.io/bash)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          go get github.com/swaggo/swag/cmd/swag
          make swag build

    
